version: 2

workflows:
  version: 2
  default:
    jobs:
      - build
      - test-basic:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - test-cb:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - cron-ci
    jobs:
      - build
      - test-basic:
          requires:
            - build
      - test-cb:
          requires:
            - build

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test-basic:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Unit Tests: npm test"
          command: npm test

  test-e2e:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Await crossbrowsertesting.com build slot"
          command: node_modules/.bin/circle-wait

      - run:
          name: "Encryption E2E tests: npm run test-crossbrowser-e2e"
          command: |
            if [ ! "${E2E_RSA_KEY:-}" ]; then echo E2E_RSA_KEY not set. Skipping... && exit 0; fi
            env E2E_CIPHERTEXT_FILE=~/repo/cipher.txt npm run test-crossbrowser-e2e

      - store_test_results:
          path: ~/repo/test/junit
      - store_artifacts:
          path: ~/repo/test/shots
      - store_artifacts:
          path: ~/repo/cipher.txt

  test-cb:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: "Await crossbrowsertesting.com build slot"
          command: node_modules/.bin/circle-wait

      - run:
          name: "Cross-browser integration tests: npm run test-crossbrowser"
          command: |
            if [ "${E2E_RSA_KEY:-}" ]; then echo E2E_RSA_KEY set. Skipping... && exit 0; fi
            npm run test-crossbrowser

      - store_test_results:
          path: ~/repo/test/junit
      - store_artifacts:
          path: ~/repo/test/shots
      - store_artifacts:
          path: ~/repo/cipher.txt
